export const users = [
  {
    id: 1,
    name: "Leslie Maya",
    email: "leslie@gmail.com",
    location: "Los Angeles, CA",
    joined: "October 2, 2010",
    role: "Admin",
    avatar: "/src/assets/avatars/avatar 1.jpg",
  },
  {
    id: 2,
    name: "Josie Deck",
    email: "josie@gmail.com",
    location: "Cheyenne, WY",
    joined: "October 3, 2011",
    role: "Admin",
    avatar: "/src/assets/avatars/avatar 2.jpg",
  },
  {
    id: 3,
    name: "Alex Pfeiffer",
    email: "alex@gmail.com",
    location: "Cheyenne, WY",
    joined: "May 20, 2015",
    role: "Admin",
    avatar: "/src/assets/avatars/avatar 3.jpg",
  },
  {
    id: 4,
    name: "Leslie Maya",
    email: "leslie.maya@gmail.com",
    location: "Los Angeles, CA",
    joined: "October 2, 2010",
    role: "Admin",
    avatar: "/src/assets/avatars/avatar 4.jpg",
  },
  {
    id: 5,
    name: "Josie Deck",
    email: "josie.deck@gmail.com",
    location: "Cheyenne, WY",
    joined: "October 3, 2011",
    role: "Admin",
    avatar: "/src/assets/avatars/avatar 5.jpg",
  },
  {
    id: 6,
    name: "Alex Pfeiffer",
    email: "alex.p@gmail.com",
    location: "Syracuse, NY",
    joined: "May 20, 2015",
    role: "Viewer",
    avatar: "/src/assets/avatars/avatar 6.jpg",
  },
  {
    id: 7,
    name: "Mike Dean",
    email: "mike.dean@gmail.com",
    location: "London, ENG",
    joined: "July 14, 2015",
    role: "Contributor",
    avatar: "/src/assets/avatars/avatar 7.jpg",
  },
  {
    id: 8,
    name: "Mateus Cunha",
    email: "cunha.m@gmail.com",
    location: "Luanda, AN",
    joined: "October, 2016",
    role: "Contributor",
    avatar: "/src/assets/avatars/avatar 8.jpg",
  },
  {
    id: 9,
    name: "Nzola Uemo",
    email: "nzola.uemo@gmail.com",
    location: "Lagos, NG",
    joined: "June 5, 2016",
    role: "Admin",
    avatar: "/src/assets/avatars/avatar 9.jpg",
  },
  // 20 إضافية
  {
    id: 10,
    name: "Sophia Lin",
    email: "sophia.lin@gmail.com",
    location: "San Francisco, CA",
    joined: "March 12, 2018",
    role: "Viewer",
    avatar: "/src/assets/avatars/avatar 10.jpg",
  },
  {
    id: 11,
    name: "Ethan Ross",
    email: "ethan.ross@gmail.com",
    location: "Austin, TX",
    joined: "July 23, 2017",
    role: "Contributor",
    avatar: "/src/assets/avatars/avatar 11.jpg",
  },
  {
    id: 12,
    name: "Mia Carter",
    email: "mia.carter@gmail.com",
    location: "Miami, FL",
    joined: "May 30, 2019",
    role: "Admin",
    avatar: "/src/assets/avatars/avatar 12.jpg",
  },
  {
    id: 13,
    name: "Liam Fox",
    email: "liam.fox@gmail.com",
    location: "New York, NY",
    joined: "January 10, 2020",
    role: "Contributor",
    avatar: "/src/assets/avatars/avatar 13.jpg",
  },
  {
    id: 14,
    name: "Olivia Bennett",
    email: "olivia.bennett@gmail.com",
    location: "Seattle, WA",
    joined: "February 5, 2019",
    role: "Viewer",
    avatar: "/src/assets/avatars/avatar 14.jpg",
  },
  {
    id: 15,
    name: "Noah Hayes",
    email: "noah.hayes@gmail.com",
    location: "Chicago, IL",
    joined: "December 11, 2018",
    role: "Admin",
    avatar: "/src/assets/avatars/avatar 15.jpg",
  },
  {
    id: 16,
    name: "Emma Liu",
    email: "emma.liu@gmail.com",
    location: "Boston, MA",
    joined: "April 22, 2017",
    role: "Contributor",
    avatar: "/src/assets/avatars/avatar 16.jpg",
  },
  {
    id: 17,
    name: "James Kim",
    email: "james.kim@gmail.com",
    location: "San Diego, CA",
    joined: "September 9, 2016",
    role: "Viewer",
    avatar: "/src/assets/avatars/avatar 17.jpg",
  },
  {
    id: 18,
    name: "Ava Thompson",
    email: "ava.thompson@gmail.com",
    location: "Denver, CO",
    joined: "June 18, 2019",
    role: "Contributor",
    avatar: "/src/assets/avatars/avatar 18.jpg",
  },
  {
    id: 19,
    name: "Lucas Martinez",
    email: "lucas.martinez@gmail.com",
    location: "Houston, TX",
    joined: "August 7, 2020",
    role: "Admin",
    avatar: "/src/assets/avatars/avatar 19.jpg",
  },
  {
    id: 20,
    name: "Chloe Rivera",
    email: "chloe.rivera@gmail.com",
    location: "Phoenix, AZ",
    joined: "March 15, 2021",
    role: "Viewer",
    avatar: "/src/assets/avatars/avatar 20.jpg",
  },
  {
    id: 21,
    name: "Henry Wilson",
    email: "henry.wilson@gmail.com",
    location: "Portland, OR",
    joined: "May 4, 2018",
    role: "Contributor",
    avatar: "/src/assets/avatars/avatar 21.jpg",
  },
  {
    id: 22,
    name: "Ella Green",
    email: "ella.green@gmail.com",
    location: "Atlanta, GA",
    joined: "July 25, 2019",
    role: "Viewer",
    avatar: "/src/assets/avatars/avatar 22.jpg",
  },
  {
    id: 23,
    name: "Daniel Moore",
    email: "daniel.moore@gmail.com",
    location: "Philadelphia, PA",
    joined: "October 30, 2017",
    role: "Admin",
    avatar: "/src/assets/avatars/avatar 23.jpg",
  },
  {
    id: 24,
    name: "Grace Hall",
    email: "grace.hall@gmail.com",
    location: "San Jose, CA",
    joined: "January 12, 2020",
    role: "Contributor",
    avatar: "/src/assets/avatars/avatar 24.jpg",
  },
  {
    id: 25,
    name: "Benjamin Scott",
    email: "benjamin.scott@gmail.com",
    location: "Dallas, TX",
    joined: "November 8, 2018",
    role: "Viewer",
    avatar: "/src/assets/avatars/avatar 25.jpg",
  },
  {
    id: 26,
    name: "Lily Adams",
    email: "lily.adams@gmail.com",
    location: "Orlando, FL",
    joined: "March 20, 2021",
    role: "Admin",
    avatar: "/src/assets/avatars/avatar 26.jpg",
  },
  {
    id: 27,
    name: "Jackson Lewis",
    email: "jackson.lewis@gmail.com",
    location: "Austin, TX",
    joined: "May 15, 2020",
    role: "Contributor",
    avatar: "/src/assets/avatars/avatar 27.jpg",
  },
  {
    id: 28,
    name: "Sofia Walker",
    email: "sofia.walker@gmail.com",
    location: "Miami, FL",
    joined: "June 6, 2019",
    role: "Viewer",
    avatar: "/src/assets/avatars/avatar 28.jpg",
  },
  {
    id: 29,
    name: "Logan Hill",
    email: "logan.hill@gmail.com",
    location: "Los Angeles, CA",
    joined: "August 22, 2020",
    role: "Admin",
    avatar: "/src/assets/avatars/avatar 29.jpg",
  },
  {
    id: 30,
    name: "Zoe Nelson",
    email: "zoe.nelson@gmail.com",
    location: "Seattle, WA",
    joined: "December 1, 2021",
    role: "Contributor",
    avatar: "/src/assets/avatars/avatar 30.jpg",
  }
];
